# -*- coding: utf-8 -*-
"""Mini Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVlJxhJUYFlut5zbv2mNCs0-8nfzqx5r

#**Smart Inventory Optimization**

---

~By

Shreyas Bailkar - A101

Kunal Shenoy - A123

Amogh Bedekar - A130
"""

import pandas as pd
import numpy as np

df = pd.read_csv('https://github.com/shreyas023/Smart_inventory/raw/main/Inventory_dataset.csv')

df.head()

df.describe()

df.nunique()

df.info()

df.isna()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['ABC_Classification'] = le.fit_transform(df['ABC_Classification'])
df['Seasonality'] = le.fit_transform(df['Seasonality'])
df['Lead_Time_Variability'] = le.fit_transform(df['Lead_Time_Variability'])
df['Warehouse_Location'] = le.fit_transform(df['Warehouse_Location'])
df['Demand_Fluctuation'] = le.fit_transform(df['Demand_Fluctuation'])

df.head()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(),cmap='YlGnBu',annot=True, center=0)
plt.title('Correlation Heatmap of Inventory Features')
plt.show()

from sklearn.model_selection import train_test_split

X = df.drop(['ABC_Classification','SKU_ID'],axis=1)
y = df['ABC_Classification']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=10)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

print('Accuracy :',np.round(accuracy_score(y_test,y_pred),decimals=4)*100,'%')